### ISSUE TITLE
Android端

### ISSUE THREAD

**Issue by Nelson-KK** [TommyLemon/UnitAuto#13]
Android端需要运行服务器代码吗

**Comment by TommyLemon** [comment]
仅手动测试是不需要的，只需要在 Android 项目集成 UnitAuto SDK
https://github.com/TommyLemon/UnitAuto#android-%E5%AE%A2%E6%88%B7%E7%AB%AF-app


但如果要管理测试用例/自动回归测试，需要部署 APIJSON 服务端用来对用例增删改查
https://github.com/TommyLemon/UnitAuto#%E9%83%A8%E7%BD%B2%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7
![image](https://user-images.githubusercontent.com/5738175/140715227-5209dbe4-db67-4f59-8168-55037737bfa7.png)

**Comment by Nelson-KK** [comment]
谢谢

**Comment by Nelson-KK** [comment]
在MVVM设计模式中，在对Android代码进行测试时，通常我们会使用Mock将 xxxService(网络请求)进行模拟以达到多方法多分支覆盖，请求这个框架是怎么处理网络请求的

**Comment by TommyLemon** [comment]
> 在对Android代码进行测试时，通常我们会使用Mock将 xxxService(网络请求)进行模拟以达到多方法多分支覆盖，请求这个框架是怎么处理网络请求的

是否 Mock 都能测试

**Comment by TommyLemon** [comment]
如果只是想体验，可以不部署 APIJSON 服务，直接用官网的
http://apijson.cn/unit
