### ISSUE TITLE
请问有没博文可以分享底层的实现原理呢？

### ISSUE THREAD

**Issue by JHuan** [TommyLemon/UnitAuto#7]
本人在业务项目中探索一些自动化的能力偶尔看到了这个项目，但时间实在不充裕，不够时间完整看完代码，想厚着脸皮问问目前有没博文介绍这个项目技术的底层原理？特别有两个点：
1.涉及的机器学习算法实现
2.不需要mock的原理

**Comment by TommyLemon** [comment]
## 1.UnitAuto 是基于 APIAuto 改造而来，机器学习零代码断言的原理、源码见
https://github.com/TommyLemon/APIAuto/blob/master/apijson/README.md#4%E8%87%AA%E5%8A%A8%E5%8C%96%E6%8E%A5%E5%8F%A3%E6%B5%8B%E8%AF%95

## 2.Mock 一般指 模拟 被测类的实例 和 被测方法的参数

### UnitAuto 构造实例有 4 种方式：
1)写代码，实现 INSTANCE_GETTER.getInstance
主要用于 Applicaiton, Context, Activity 等环境相关类

2)不写代码，传 this 字段来模拟
"this": {  // 符合对应类型的结构
   "id": 1
}

3)不写代码，自动调用构造方法 Class.newInstance

4)不写代码，手动调用获取实例方法
"contructor": "getInstance"
主要用于单例模式类


UnitAuto 模拟参数有 3 种方式：
1)管理工具界面一键导入用例时，MethodUtil 会根据类型来随机生成值


2)管理工具界面 左侧 JSON 输入框可手动输入 JSON 格式的 实例值、参数值 等


3)管理工具界面 左下方随机配置区域，支持 随机测试 和 顺序测试，通过 简单配置 来快速构造各种参数

**Comment by JHuan** [comment]
多谢回复~！我先拜读
